added maven java 21

diff --git a/.github/workflows/29-pr-automerge.yml b/.github/workflows/29-pr-automerge.yml
--- a/.github/workflows/29-pr-automerge.yml
+++ b/.github/workflows/29-pr-automerge.yml
@@ -50,14 +50,25 @@ jobs:
           
           if [ "$RESPONSE" -eq 200 ]; then
             echo "List pull request"
-            success()
           elif [ "$RESPONSE" -eq 401 ]; then
             echo "Bad credentials"
-            failure()
+            exit 1
           else
             echo "Failed to approve PR. HTTP status code: $RESPONSE"
-            failure()
+            exit 1
           fi
+      - name: I will be skipped
+        if: ${{ success() }}
+        run: echo "I will print if previous steps succeed."
+      - name: I will execute
+        if: ${{ failure() }}
+        run: echo "I will print if any previous step fails."
+      - name: I will execute
+        if: ${{ !cancelled() }}
+        run: echo "I will always print, except when the workflow is cancelled."
+      - name: I will execute when cancelled
+        if: ${{ cancelled() }}
+        run: echo "I will print if the workflow has been cancelled."
 
   settings-xml:
     runs-on: ubuntu-latest
