Call APi and get response

diff --git a/.github/workflows/29-pr-automerge.yml b/.github/workflows/29-pr-automerge.yml
--- a/.github/workflows/29-pr-automerge.yml
+++ b/.github/workflows/29-pr-automerge.yml
@@ -119,7 +119,36 @@ jobs:
       - name: I will execute when cancelled
         if: ${{ cancelled() }}
         run: echo "I will print if the workflow has been cancelled."
-
+  auto-approve-pr-test-3-response:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Call Composite Action
+        id: call-composite
+        uses: ./.github/actions/automerge-composite
+      - name: Use Composite Action Output
+        run: |
+          echo "The response code is ${{ steps.call-composite.outputs.response }}"
+          if [ ${{ steps.call-composite.outputs.response }} -eq 200 ]; then
+            echo "PR approved"
+          elif [ ${{ steps.call-composite.outputs.response }} -eq 401 ]; then
+            echo "Bad credentials"
+            exit 1
+          else
+            echo "Failed to approve PR. HTTP status code: ${{ steps.call-composite.outputs.response }}"
+            exit 1
+          fi
+      - name: I will be skipped
+        if: ${{ success() }}
+        run: echo "I will print if previous steps succeed."
+      - name: I will execute
+        if: ${{ failure() }}
+        run: echo "I will print if any previous step fails."
+      - name: I will execute
+        if: ${{ !cancelled() }}
+        run: echo "I will always print, except when the workflow is cancelled."
+      - name: I will execute when cancelled
+        if: ${{ cancelled() }}
+        run: echo "I will print if the workflow has been cancelled."
   settings-xml:
     runs-on: ubuntu-latest
     steps:
