added maven java 21

diff --git a/.github/workflows/29-pr-automerge.yml b/.github/workflows/29-pr-automerge.yml
--- a/.github/workflows/29-pr-automerge.yml
+++ b/.github/workflows/29-pr-automerge.yml
@@ -9,11 +9,29 @@ jobs:
     steps:
       - name: Auto approve PR
         run: |
-          curl -X POST -H "Authorization: Bearer ${{ secrets.GH_TOKEN_PR_AUTOMERGE}}" \
+          curl -X POST -H "Authorization: Bearer ${{ secrets.GH_TOKEN_PR_AUTOMERGE }}" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/ivosahlik/github-actions-sample/pulls/${{ github.event.pull_request.number }}/reviews \
             -d '{"event":"APPROVE", "body": "Approved by GHA workflow: Auto approve test installations"}'
           echo "PR approved"
+
+  auto-approve-pr-test-response:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Auto approve PR TEST 1
+        run: |
+          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST -H "Authorization: Bearer ${{ secrets.GH_TOKEN_PR_AUTOMERGE }}" \
+            -H "Accept: application/vnd.github.v3+json" \
+            https://api.github.com/repos/ivosahlik/github-actions-sample/pulls/${{ github.event.pull_request.number }}/reviews \
+            -d '{"event":"APPROVE", "body": "Approved by GHA workflow: Auto approve test installations"}')
+          
+          if [ "$RESPONSE" -eq 200 ]; then
+            echo "PR approved"
+            echo "Pull request [${{ github.event.pull_request.number }}](https://github.com/VFCZ-Digital/dxl-configurations/pull/${{ github.event.pull_request.number }}) is automatically approved, as there are only pre-approved files." >> $GITHUB_STEP_SUMMARY
+          else
+            echo "Failed to approve PR. HTTP status code: $RESPONSE"
+            exit 1
+          fi
 
   settings-xml:
     runs-on: ubuntu-latest
