Call APi and get response

diff --git a/.github/workflows/29-pr-automerge.yml b/.github/workflows/29-pr-automerge.yml
--- a/.github/workflows/29-pr-automerge.yml
+++ b/.github/workflows/29-pr-automerge.yml
@@ -90,7 +90,7 @@ jobs:
   auto-approve-pr-test-2-response:
     runs-on: ubuntu-latest
     steps:
-      - name: Auto approve PR TEST 2
+      - name: List pull requests - TEST 2
         run: |
           RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X GET -H "Authorization: Bearer ${{ secrets.GH_TOKEN_PR_AUTOMERGE }}" \
             -H "Accept: application/vnd.github.v3+json" \
@@ -141,6 +141,43 @@ jobs:
             exit 1
           else
             echo "Failed to approve PR. HTTP status code: ${{ steps.call-composite.outputs.response }}"
+            exit 1
+          fi
+
+      - name: I will be skipped
+        if: ${{ success() }}
+        run: echo "I will print if previous steps succeed."
+      - name: I will execute
+        if: ${{ failure() }}
+        run: echo "I will print if any previous step fails."
+      - name: I will execute
+        if: ${{ !cancelled() }}
+        run: echo "I will always print, except when the workflow is cancelled."
+      - name: I will execute when cancelled
+        if: ${{ cancelled() }}
+        run: echo "I will print if the workflow has been cancelled."
+  list-pull-requests-test-4-call-api:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check out the repo
+        uses: actions/checkout@v3
+
+      - name: Call Composite Action
+        id: list-pull-requests
+        uses: ./.github/actions/list-pull-requests
+        with:
+          secret: ${{ secrets.GH_TOKEN_PR_AUTOMERGE }}
+
+      - name: Use Composite Action Output
+        run: |
+          echo "The response code is ${{ steps.list-pull-requests.outputs.response }}"
+          if [ ${{ steps.list-pull-requests.outputs.response }} -eq 200 ]; then
+            echo "PR approved"
+          elif [ ${{ steps.list-pull-requests.outputs.response }} -eq 401 ]; then
+            echo "Bad credentials"
+            exit 1
+          else
+            echo "Failed to approve PR. HTTP status code: ${{ steps.list-pull-requests.outputs.response }}"
             exit 1
           fi
 
