Call APi and get response

diff --git a/.github/workflows/29-pr-automerge.yml b/.github/workflows/29-pr-automerge.yml
--- a/.github/workflows/29-pr-automerge.yml
+++ b/.github/workflows/29-pr-automerge.yml
@@ -15,6 +15,40 @@ jobs:
             -d '{"event":"APPROVE", "body": "Approved by GHA workflow: Auto approve test installations"}'
           echo "PR approved"
 
+  pass-response:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Call APi and get response
+        id: get-response
+        run: |
+          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST -H "Authorization: Bearer ${{ secrets.GH_TOKEN_PR_AUTOMERGE }}" \
+            -H "Accept: application/vnd.github.v3+json" \
+            https://api.github.com/repos/ivosahlik/github-actions-sample/pulls/${{ github.event.pull_request.number }}/reviews \
+            -d '{"event":"APPROVE", "body": "Approved by GHA workflow: Auto approve test installations"}')
+          echo "response=$RESPONSE" >> $GITHUB_ENV
+      - name: Check response
+        run: |
+          if [ "${{ env.response }}" -eq 200 ]; then
+            echo "PR approved"
+          elif [ "${{ env.response }}" -eq 401 ]; then
+            echo "Bad credentials"
+            exit 1
+          else
+            echo "Failed to approve PR. HTTP status code: ${{ env.response }}"
+            exit 1
+      - name: I will be skipped
+        if: ${{ success() }}
+        run: echo "I will print if previous steps succeed."
+      - name: I will execute
+        if: ${{ failure() }}
+        run: echo "I will print if any previous step fails."
+      - name: I will execute
+        if: ${{ !cancelled() }}
+        run: echo "I will always print, except when the workflow is cancelled."
+      - name: I will execute when cancelled
+        if: ${{ cancelled() }}
+        run: echo "I will print if the workflow has been cancelled."
+
   auto-approve-pr-test-1-response:
     runs-on: ubuntu-latest
     steps:
